-- Seed data for AgentFlow final scenario test
-- This file is auto-generated by setup.ps1 or setup.sh with real user UUIDs
-- DO NOT manually edit user IDs - run the setup script instead
--
-- Setup:
-- Windows:  powershell -ExecutionPolicy Bypass -File nhost/seeds/default/setup.ps1
-- Linux:    bash nhost/seeds/default/setup.sh
--
-- This script will:
-- 1. Create test users in Nhost Auth
-- 2. Generate this file with real user IDs
-- 3. Run nhost db seed to populate database

-- Insert organizations
INSERT INTO public.organizations (id, name, calls_used, calls_allowed) VALUES
  ('11111111-1111-1111-1111-111111111111', 'Org A', 0, 1000),
  ('22222222-2222-2222-2222-222222222222', 'Org B', 0, 1000);

-- PLACEHOLDER USER IDS - populated by setup script
-- These should be real auth.users.id values after running setup
INSERT INTO public.org_members (org_id, user_id, role) VALUES
  ('11111111-1111-1111-1111-111111111111', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'owner'),
  ('11111111-1111-1111-1111-111111111111', 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'editor'),
  ('22222222-2222-2222-2222-222222222222', 'cccccccc-cccc-cccc-cccc-cccccccccccc', 'owner');

-- Org A: Sample workflow with llm_call, http_request, conditional_branch, approval_gate
INSERT INTO public.workflows (id, org_id, name, description, created_by, is_enabled) VALUES
  ('33333333-3333-3333-3333-333333333333', '11111111-1111-1111-1111-111111111111', 'AI Analysis Workflow', 'Analyzes input with LLM, calls API, branches on result, requires approval', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', true);

-- Workflow steps for Org A
INSERT INTO public.workflow_steps (id, workflow_id, org_id, position, type, config) VALUES
  ('44444444-4444-4444-4444-444444444444', '33333333-3333-3333-3333-333333333333', '11111111-1111-1111-1111-111111111111', 0, 'llm_call', '{"prompt": "Is this approved? Analyze: {{context}}."}'),
  ('55555555-5555-5555-5555-555555555555', '33333333-3333-3333-3333-333333333333', '11111111-1111-1111-1111-111111111111', 1, 'http_request', '{"url": "https://httpbin.org/post", "method": "POST", "headers": {"content-type": "application/json"}}'),
  ('66666666-6666-6666-6666-666666666666', '33333333-3333-3333-3333-333333333333', '11111111-1111-1111-1111-111111111111', 2, 'conditional_branch', '{"contains": "approved"}'),
  ('77777777-7777-7777-7777-777777777777', '33333333-3333-3333-3333-333333333333', '11111111-1111-1111-1111-111111111111', 3, 'approval_gate', '{}');

-- Org A: Workflow triggers
INSERT INTO public.workflow_triggers (id, workflow_id, org_id, type, config, enabled) VALUES
  ('88888888-8888-8888-8888-888888888888', '33333333-3333-3333-3333-333333333333', '11111111-1111-1111-1111-111111111111', 'manual', '{}', true),
  ('99999999-9999-9999-9999-999999999999', '33333333-3333-3333-3333-333333333333', '11111111-1111-1111-1111-111111111111', 'webhook', '{"secret": "webhook-secret-org-a"}', true);

-- SETUP INSTRUCTIONS:
-- Automated: Run setup script to create users and populate real IDs
--   bash nhost/seeds/default/setup.sh
--
-- OR Manual: Create 3 test users in Hasura Console (http://localhost:1337)
--   - alice@test.local / password123
--   - bob@test.local / password123  
--   - charlie@test.local / password123
--   Then replace placeholder UUIDs below with real auth.users.id values
--
-- Then run: nhost db seed
--   - Replace cccccccc-cccc-cccc-cccc-cccccccccccc with charlie's user ID
--
-- Step 3: Run this seed
--   psql postgresql://postgres:postgres@localhost:5432/postgres -f nhost/seeds/default/seed.sql
--
-- Step 4: Test in UI
--   - Frontend: http://localhost:3000
--   - Log in as alice (Org A owner) - should see workflow
--   - Log in as charlie (Org B owner) - should NOT see Org A workflows
--   - Run workflow as owner, watch pause at approval_gate
--   - Approve as editor, watch resume and complete
--
-- Step 5: Test webhook
--   curl -X POST http://localhost:3000/webhookTrigger \
--     -H "Content-Type: application/json" \
--     -d '{"secret":"webhook-secret-org-a"}'

